services:
  docs:
    image: lms_local_local_docs
    container_name: lms_local_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./lms_local:/app/lms_local:z
    ports:
      - '9000:9000'
    command: /start-docs
